=== UKHomeOffice/eba-envbuild-tool/eba-visio/src/AgnosticCloudConfig-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by Home Office (Home Office) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" targetNamespace="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GeographicContainer" type="GeographicContainerType">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="GeographicContainerType">
		<xs:sequence>
			<xs:element name="account" type="xs:string"/>
			<xs:element name="region" type="xs:string"/>
			<xs:element name="EnvironmentContainer" type="EnvironmentContainerType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentContainerType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="provider" type="ProviderType"/>
			<xs:element name="Environment" type="EnvironmentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:sequence>
				<xs:element name="EnvironmentContainerDefinition" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="EnvironmentContainerDefinitionType">
								<xs:sequence>
									<xs:element name="name" type="xs:string"/>
									<xs:element name="version" type="xs:string"/>
									<xs:element name="Network" type="OrganisationalNetworkType" minOccurs="0" maxOccurs="unbounded"/>
									<xs:element name="Gateway" type="GatewayType" minOccurs="0" maxOccurs="unbounded"/>
									<xs:element name="DataCenter" type="DataCenterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="notes" type="xs:string"/>
			<xs:element name="EnvironmentDefinition" type="EnvironmentDefinitionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="environmentContainerDefinitionId" type="xs:IDREF"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentContainerDefinitionType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:simpleType name="NetworkTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Application"/>
			<xs:enumeration value="Organisation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="NetworkType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="fenceMode" type="xs:string"/>
			<xs:element name="networkMask" type="xs:string"/>
			<xs:element name="gatewayAddress" type="xs:string"/>
			<xs:element name="primaryDns" type="xs:string"/>
			<xs:element name="secondaryDns" type="xs:string"/>
			<xs:element name="dnsSuffix" type="xs:string"/>
			<xs:element name="staticIpPool" type="xs:string"/>
			<xs:element name="ipRangeStart" type="xs:string"/>
			<xs:element name="ipRangeEnd" type="xs:string"/>
			<xs:element name="CIDR" type="xs:string"/>
			<xs:element name="shared" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="dataCenterId" type="xs:IDREF"/>
		<xs:attribute name="dataCenterName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ApplicationNetworkType">
		<xs:complexContent>
			<xs:extension base="NetworkType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="OrganisationalNetworkType">
		<xs:complexContent>
			<xs:extension base="NetworkType">
				<xs:sequence minOccurs="0">
					<xs:element name="peerNetworkName" type="xs:string"/>
					<xs:element name="peerEnvironmentName" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="gatewayId" type="xs:IDREF"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EnvironmentDefinitionComplexType">
		<xs:sequence>
			<xs:element name="EnvironmentDefinitionType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnvironmentDefinitionType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="version" type="xs:string"/>
			<xs:element name="cidr" type="xs:string"/>
			<xs:element name="VirtualMachineContainer" type="VirtualMachineContainerType" maxOccurs="unbounded"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="environmentDefinitionType" type="EnvironmentDefinitionTypeType" use="required"/>
	</xs:complexType>
	<xs:simpleType name="EnvironmentDefinitionTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Logical"/>
			<xs:enumeration value="Blueprint"/>
			<xs:enumeration value="Physical"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="VirtualMachineContainerType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="runtimeLease" type="xs:string"/>
			<xs:element name="storageLease" type="xs:string"/>
			<xs:element name="serviceLevel" type="xs:string"/>
			<xs:element name="powerOn" type="xs:boolean"/>
			<xs:element name="deploy" type="xs:boolean"/>
			<xs:element name="domain" type="xs:string"/>
			<xs:element name="VirtualMachine" type="VirtualMachineType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Network" type="ApplicationNetworkType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="dataCenterId" type="xs:IDREF"/>
		<xs:attribute name="dataCenterName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="MetaDataType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="VirtualMachineType">
		<xs:sequence>
			<xs:element name="vmName" type="xs:string"/>
			<xs:element name="computerName" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="templateName" type="xs:string"/>
			<xs:element name="templateServiceLevel" type="xs:string"/>
			<xs:element name="storageProfile" type="xs:string"/>
			<xs:element name="customisationScript" type="xs:string"/>
			<xs:element name="VMOrder" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The order of the VM in in the sequence for powering on (ascending order) and off (reversed order high to low)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="1000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStartDelay" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The Start delay</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStopDelay" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The Stop delay in seconds</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStartAction" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The VM Start Action. One of none, powerOn</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="powerOn">
							<xs:annotation>
								<xs:documentation>This will set the VM to Power On when started by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="none">
							<xs:annotation>
								<xs:documentation>This will set the VM do nothing when started by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStopAction" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The VM Stop Action. One of powerOff, guestShutdown</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="powerOff">
							<xs:annotation>
								<xs:documentation>This will set the VM to Power Off when stopped by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="guestShutdown">
							<xs:annotation>
								<xs:documentation>This will set the VM to Shutdown when stopped by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="cpuCount" type="xs:integer"/>
			<xs:element name="memory" type="xs:integer"/>
			<xs:element name="memoryUnit" type="xs:string"/>
			<xs:element name="hardwareProfile" type="xs:string"/>
			<xs:element name="hatype" type="xs:string" minOccurs="0"/>
			<xs:element name="Storage" type="StorageType" maxOccurs="unbounded"/>
			<xs:element name="NIC" type="NICType" maxOccurs="unbounded"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="NICType">
		<xs:sequence>
			<xs:element name="indexNumber" type="xs:integer"/>
			<xs:element name="primary" type="xs:boolean"/>
			<xs:element name="ipAssignment" type="xs:string"/>
			<xs:element name="Interface" type="InterfaceType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="networkID" type="xs:IDREF"/>
		<xs:attribute name="networkName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="StorageType">
		<xs:sequence>
			<xs:element name="indexNumber" type="xs:integer"/>
			<xs:element name="size" type="xs:integer"/>
			<xs:element name="sizeUnit" type="xs:string"/>
			<xs:element name="busType" type="xs:string"/>
			<xs:element name="busSubType" type="xs:string"/>
			<xs:element name="deviceMount" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="DataCenterType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="GatewayType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="NAT" type="NATType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="NATType">
		<xs:sequence>
			<xs:element name="appliedOn" type="xs:string"/>
			<xs:element name="originalSourceIpOrRange" type="xs:string"/>
			<xs:element name="translatedSourceIpOrRange" type="xs:string"/>
			<xs:element name="enabled" type="xs:boolean"/>
			<xs:element name="DNAT" type="DNATType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="DNATType">
		<xs:sequence>
			<xs:element name="translatedPort" type="xs:string"/>
			<xs:element name="protocolType" type="xs:string"/>
			<xs:element name="protocolOriginalPort" type="xs:string"/>
			<xs:element name="protocolIcmpType" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:simpleType name="ProviderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SKYSCAPE"/>
			<xs:enumeration value="AWS"/>
			<xs:enumeration value="MICROSOFTAZURE"/>
			<xs:enumeration value="GOOGLECOMPUTE"/>
			<xs:enumeration value="IBMSOFTLAYER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="InterfaceType">
		<xs:sequence>
			<xs:element name="interfaceNumber" type="xs:integer" minOccurs="0"/>
			<xs:element name="staticIpPool" type="xs:string"/>
			<xs:element name="networkMask" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="staticIpAddress" type="xs:string"/>
			<xs:element name="isVip" type="xs:boolean"/>
			<xs:element name="VRRP" type="xs:integer" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== UKHomeOffice/eba-envbuild-tool/eba-acloud/aCloudClient/src/test/resources/aws/awsTestEnvironment.xml
<?xml version="1.0" encoding="UTF-8"?>
<GeographicContainer id="GeographicContainer_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" xsi:schemaLocation="http://ebsa.ipt.com/AgnosticCloudConfig-1.0 AgnosticCloudConfig-1.0.xsd">
	<account>Homeoffice</account>
	<region>eu-west-1</region>
	<EnvironmentContainer id="EnvironmentContainer_1">
		<name>AmazonTest</name>
		<providor>AMAZONWEBSERVICES</providor>
		<Environment id="Environment_1" environmentContainerDefinitionId="EnvironmentContainerDefinition_1">
			<name>AmazonTest</name>
			<notes>Environment to test the amazon machines and networks for testing</notes>
			<cidr>10.16.0.0/16</cidr>
			<EnvironmentDefinition environmentDefinitionTypeType="Physical" id="EnvironmentDefinition_1">
				<name>Test1</name>
				<version>1</version>
				
				<VirtualMachineContainer id="VirtualMachineContainer_MEBC_1" dataCenterId="DataCenter_1">
					<name>TEST_VMC</name>
					<description>TEST_VMC container</description>
					<runtimeLease>String</runtimeLease>
					<storageLease>String</storageLease>
					<serviceLevel>String</serviceLevel>
					<powerOn>true</powerOn>
					<deploy>true</deploy>
					<domain>test.local</domain>
					<VirtualMachine id="VirtualMachine_MEBC_1">
						<vmName>testvm1</vmName>
						<computerName>testvm1</computerName>
						<description>Test VM 1</description>
						<templateName>ami-abb22edc</templateName>
						<templateServiceLevel>String</templateServiceLevel>
						<storageProfile>String</storageProfile>
						<customisationScript>script.sh</customisationScript>
						<cpuCount>2</cpuCount>
						<memory>4096</memory>
						<memoryUnit>MB</memoryUnit>
						<hardwareProfile>m3.large</hardwareProfile>
						<hatype>NA</hatype>
						<Storage id="Storage_testvm1_0">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sda1</deviceMount>
						</Storage>
						<Storage id="Storage_testvm1_1">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sdh</deviceMount>
						</Storage>
						<NIC networkID="TEST_ORG_NET_1" id="Nic_testvm1_0">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<name>testvm1nic0</name>
							<ipAssignment>10.16.0.4</ipAssignment>
							<staticIpAddress>10.16.0.4</staticIpAddress>
							<vip>NA</vip>
						</NIC>
						<NIC networkID="TEST_APP_NET_1" id="Nic_testvm1_1">
							<indexNumber>1</indexNumber>
							<primary>false</primary>
							<name>testvm1nic1</name>
							<ipAssignment>10.16.1.4</ipAssignment>
							<staticIpAddress>10.16.1.4</staticIpAddress>
							<vip>NA</vip>
						</NIC>
						<NIC networkID="TEST_APP_NET_2" id="Nic_testvm1_2">
							<indexNumber>2</indexNumber>
							<primary>false</primary>
							<name>testvm1nic2</name>
							<ipAssignment>10.16.2.4</ipAssignment>
							<staticIpAddress>10.16.2.4</staticIpAddress>
							<vip>NA</vip>
						</NIC>
					</VirtualMachine>
					<Network id="TEST_APP_NET_1" dataCenterId="DataCenter_1">
						<name>TEST_APP_NET_1</name>
						<description>Test Application Subnet 1</description>
						<fenceMode>String</fenceMode>
						<networkMask>String</networkMask>
						<gatewayAddress>10.16.1.1</gatewayAddress>
						<primaryDns>String</primaryDns>
						<secondaryDns>String</secondaryDns>
						<dnsSuffix>String</dnsSuffix>
						<staticIpPool>String</staticIpPool>
						<ipRangeStart>String</ipRangeStart>
						<ipRangeEnd>String</ipRangeEnd>
						<CIDR>10.16.1.0/24</CIDR>
						<shared>true</shared>
					</Network>
					<Network id="TEST_APP_NET_2" dataCenterId="DataCenter_1">
						<name>TEST_APP_NET_2</name>
						<description>Test Application Subnet 2</description>
						<fenceMode>String</fenceMode>
						<networkMask>String</networkMask>
						<gatewayAddress>10.16.2.1</gatewayAddress>
						<primaryDns>String</primaryDns>
						<secondaryDns>String</secondaryDns>
						<dnsSuffix>String</dnsSuffix>
						<staticIpPool>String</staticIpPool>
						<ipRangeStart>String</ipRangeStart>
						<ipRangeEnd>String</ipRangeEnd>
						<CIDR>10.16.2.0/24</CIDR>
						<shared>true</shared>
					</Network>
				</VirtualMachineContainer>
			</EnvironmentDefinition>
		</Environment>
		<EnvironmentContainerDefinition id="EnvironmentContainerDefinition_1">
			<name>AmazonPoC_Environment_Definition</name>
			<version>1</version>
			
			<Network id="TEST_ORG_NET_1" gatewayId="AwsTestGatway_1" dataCenterId="DataCenter_1">
				<name>TEST_NET_1</name>
				<description>Organisation Network, Public Subnet</description>
				<fenceMode>String</fenceMode>
				<networkMask>String</networkMask>
				<gatewayAddress>10.16.0.1</gatewayAddress>
				<primaryDns>String</primaryDns>
				<secondaryDns>String</secondaryDns>
				<dnsSuffix>String</dnsSuffix>
				<staticIpPool>String</staticIpPool>
				<ipRangeStart>String</ipRangeStart>
				<ipRangeEnd>String</ipRangeEnd>
				<CIDR>10.16.0.0/24</CIDR>
				<shared>true</shared>
			</Network>
			<Gateway id="AwsTestGatway_1">
				<name>Amazon_TEST_gateway</name>
				<NAT id="ID_201">
					<appliedOn>String</appliedOn>
					<originalSourceIpOrRange>String</originalSourceIpOrRange>
					<translatedSourceIpOrRange>String</translatedSourceIpOrRange>
					<enabled>true</enabled>
					<DNAT id="ID_202">
						<translatedPort>String</translatedPort>
						<protocolType>String</protocolType>
						<protocolOriginalPort>String</protocolOriginalPort>
						<protocolIcmpType>String</protocolIcmpType>
					</DNAT>
				</NAT>
			</Gateway>
			<DataCenter id="DataCenter_1">
				<name>eu-west-1a</name>
			</DataCenter>
		</EnvironmentContainerDefinition>
	</EnvironmentContainer>
</GeographicContainer>

=== UKHomeOffice/eba-envbuild-tool/eba-acloud/aCloudClient/src/test/resources/aws/startupShutdownConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<GeographicContainer id="ID_1" xsi:schemaLocation="http://ebsa.ipt.com/AgnosticCloudConfig-1.0 AgnosticCloudConfig-1.0.xsd" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<account>UNITTESTEBSA</account>
	<region>eu-west-1</region>
	<EnvironmentContainer id="ID_2">
		<name>UNITTESTContainer</name>
		<provider>AWS</provider>
		<Environment environmentContainerDefinitionId="ID_13" id="ID_3">
			<name>UNITTEST_SUSD_ENVIRONMENT</name>
			<notes>notes</notes>
			<EnvironmentDefinition environmentDefinitionType="Physical" id="ID_4">
				<name>UNITTEST_SUSD_ENVIRONMENT_DEFINITION</name>
				<version>1.0</version>
				<cidr>10.16.0.0/16</cidr>
				<VirtualMachineContainer dataCenterName="String" dataCenterId="datacentre_1" id="ID_5">
					<name>UNITTEST_SUSD_TEST_VMC</name>
					<description>test vmc</description>
					<runtimeLease>String</runtimeLease>
					<storageLease>String</storageLease>
					<serviceLevel>String</serviceLevel>
					<powerOn>true</powerOn>
					<deploy>true</deploy>
					<domain>test.domain.local</domain>
					<VirtualMachine id="VM_1">
						<vmName>UNITTEST_SUSD_testvm1</vmName>
						<computerName>UNITTEST_SUSD_testvm1</computerName>
						<description>testvm1 description</description>
						<templateName>ami-08acfa7f</templateName>
						<templateServiceLevel>String</templateServiceLevel>
						<storageProfile>String</storageProfile>
						<customisationScript></customisationScript>
						<VMOrder>0</VMOrder>
						<VMStartDelay>0</VMStartDelay>
						<VMStopDelay>0</VMStopDelay>
						<VMStartAction>none</VMStartAction>
						<VMStopAction>guestShutdown</VMStopAction>
						<cpuCount>0</cpuCount>
						<memory>0</memory>
						<memoryUnit>String</memoryUnit>
						<hardwareProfile>m3.large</hardwareProfile>
						<hatype>String</hatype>
						<Storage id="VM_1_DISK_1">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sda1</deviceMount>
						</Storage>
						<NIC networkID="APP_NET_1" networkName="String" id="VM_1_NIC_1">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<ipAssignment>String</ipAssignment>
							<Interface>
								<interfaceNumber>0</interfaceNumber>
								<staticIpPool>String</staticIpPool>
								<networkMask>String</networkMask>
								<name>susdTestNic1</name>
								<staticIpAddress>10.16.100.4</staticIpAddress>
								<isVip>false</isVip>
								<VRRP>0</VRRP>
							</Interface>
						</NIC>
					</VirtualMachine>
					<VirtualMachine id="VM_2">
						<vmName>UNITTEST_SUSD_testvm2</vmName>
						<computerName>UNITTEST_SUSD_testvm2</computerName>
						<description>testvm2 description</description>
						<templateName>ami-08acfa7f</templateName>
						<templateServiceLevel>String</templateServiceLevel>
						<storageProfile>String</storageProfile>
						<customisationScript></customisationScript>
						<VMOrder>0</VMOrder>
						<VMStartDelay>0</VMStartDelay>
						<VMStopDelay>0</VMStopDelay>
						<VMStartAction>none</VMStartAction>
						<VMStopAction>guestShutdown</VMStopAction>
						<cpuCount>0</cpuCount>
						<memory>0</memory>
						<memoryUnit>String</memoryUnit>
						<hardwareProfile>m3.large</hardwareProfile>
						<hatype>String</hatype>
						<Storage id="VM_2_DISK_1">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sda1</deviceMount>
						</Storage>
						<NIC networkID="APP_NET_1" networkName="String" id="VM_2_NIC_1">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<ipAssignment>String</ipAssignment>
							<Interface>
								<interfaceNumber>0</interfaceNumber>
								<staticIpPool>String</staticIpPool>
								<networkMask>String</networkMask>
								<name>susdTestNic1</name>
								<staticIpAddress>10.16.100.5</staticIpAddress>
								<isVip>false</isVip>
								<VRRP>0</VRRP>
							</Interface>
						</NIC>
					</VirtualMachine>
					<VirtualMachine id="VM_3">
						<vmName>UNITTEST_SUSD_testvm3</vmName>
						<computerName>UNITTEST_SUSD_testvm3</computerName>
						<description>testvm3 description</description>
						<templateName>ami-08acfa7f</templateName>
						<templateServiceLevel>String</templateServiceLevel>
						<storageProfile>String</storageProfile>
						<customisationScript></customisationScript>
						<VMOrder>0</VMOrder>
						<VMStartDelay>0</VMStartDelay>
						<VMStopDelay>0</VMStopDelay>
						<VMStartAction>none</VMStartAction>
						<VMStopAction>guestShutdown</VMStopAction>
						<cpuCount>0</cpuCount>
						<memory>0</memory>
						<memoryUnit>String</memoryUnit>
						<hardwareProfile>m3.large</hardwareProfile>
						<hatype>String</hatype>
						<Storage id="VM_3_DISK_1">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sda1</deviceMount>
						</Storage>
						<NIC networkID="APP_NET_1" networkName="String" id="VM_3_NIC_1">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<ipAssignment>String</ipAssignment>
							<Interface>
								<interfaceNumber>0</interfaceNumber>
								<staticIpPool>String</staticIpPool>
								<networkMask>String</networkMask>
								<name>susdTestNic1</name>
								<staticIpAddress>10.16.100.6</staticIpAddress>
								<isVip>false</isVip>
								<VRRP>0</VRRP>
							</Interface>
						</NIC>
					</VirtualMachine>
					<VirtualMachine id="VM_4">
						<vmName>UNITTEST_SUSD_testvm4</vmName>
						<computerName>UNITTEST_SUSD_testvm4</computerName>
						<description>testvm4 description</description>
						<templateName>ami-08acfa7f</templateName>
						<templateServiceLevel>String</templateServiceLevel>
						<storageProfile>String</storageProfile>
						<customisationScript></customisationScript>
						<VMOrder>0</VMOrder>
						<VMStartDelay>0</VMStartDelay>
						<VMStopDelay>0</VMStopDelay>
						<VMStartAction>none</VMStartAction>
						<VMStopAction>guestShutdown</VMStopAction>
						<cpuCount>0</cpuCount>
						<memory>0</memory>
						<memoryUnit>String</memoryUnit>
						<hardwareProfile>m3.large</hardwareProfile>
						<hatype>String</hatype>
						<Storage id="VM_4_DISK_1">
							<indexNumber>0</indexNumber>
							<size>50</size>
							<sizeUnit>GB</sizeUnit>
							<busType>String</busType>
							<busSubType>String</busSubType>
							<deviceMount>/dev/sda1</deviceMount>
						</Storage>
						<NIC networkID="APP_NET_1" networkName="String" id="VM_4_NIC_1">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<ipAssignment>String</ipAssignment>
							<Interface>
								<interfaceNumber>0</interfaceNumber>
								<staticIpPool>String</staticIpPool>
								<networkMask>String</networkMask>
								<name>susdTestNic1</name>
								<staticIpAddress>10.16.100.7</staticIpAddress>
								<isVip>false</isVip>
								<VRRP>0</VRRP>
							</Interface>
						</NIC>
					</VirtualMachine>
					<Network dataCenterName="String" dataCenterId="datacentre_1" id="APP_NET_1">
						<name>UNITTEST_SUSD_TEST_APP_NET_1</name>
						<description>test net 1 desc</description>
						<fenceMode>String</fenceMode>
						<networkMask>String</networkMask>
						<gatewayAddress>String</gatewayAddress>
						<primaryDns>10.0.0.0</primaryDns>
						<secondaryDns>String</secondaryDns>
						<dnsSuffix>String</dnsSuffix>
						<staticIpPool>String</staticIpPool>
						<ipRangeStart>String</ipRangeStart>
						<ipRangeEnd>String</ipRangeEnd>
						<CIDR>10.16.100.0/24</CIDR>
						<shared>false</shared>
					</Network>
				</VirtualMachineContainer>
			</EnvironmentDefinition>
		</Environment>
		<EnvironmentContainerDefinition id="ID_13">
			<name>SUSH_ENVIRONMENT_DEFINITION</name>
			<version>1.0</version>
			<Network dataCenterName="String" dataCenterId="datacentre_1" id="ID_14">
				<name>UNITTEST_SUSD_TEST_ORG_NET_1</name>
				<description>test org net</description>
				<fenceMode>String</fenceMode>
				<networkMask>String</networkMask>
				<gatewayAddress>String</gatewayAddress>
				<primaryDns>10.0.0.0</primaryDns>
				<secondaryDns>10.0.0.0</secondaryDns>
				<dnsSuffix>String</dnsSuffix>
				<staticIpPool>String</staticIpPool>
				<ipRangeStart>String</ipRangeStart>
				<ipRangeEnd>String</ipRangeEnd>
				<CIDR>10.16.101.0/24</CIDR>
				<shared>false</shared>
			</Network>
			<DataCenter id="datacentre_1">
				<name>eu-west-1a</name>
			</DataCenter>
		</EnvironmentContainerDefinition>
	</EnvironmentContainer>
</GeographicContainer>
