=== UKHomeOffice/eba-envbuild-tool/eba-visio/src/AgnosticCloudConfig-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 sp1 (http://www.altova.com) by Home Office (Home Office) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" targetNamespace="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="GeographicContainer" type="GeographicContainerType">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="GeographicContainerType">
		<xs:sequence>
			<xs:element name="account" type="xs:string"/>
			<xs:element name="region" type="xs:string"/>
			<xs:element name="EnvironmentContainer" type="EnvironmentContainerType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentContainerType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="provider" type="ProviderType"/>
			<xs:element name="Environment" type="EnvironmentType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:sequence>
				<xs:element name="EnvironmentContainerDefinition" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:complexContent>
							<xs:extension base="EnvironmentContainerDefinitionType">
								<xs:sequence>
									<xs:element name="name" type="xs:string"/>
									<xs:element name="version" type="xs:string"/>
									<xs:element name="Network" type="OrganisationalNetworkType" minOccurs="0" maxOccurs="unbounded"/>
									<xs:element name="Gateway" type="GatewayType" minOccurs="0" maxOccurs="unbounded"/>
									<xs:element name="DataCenter" type="DataCenterType" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:extension>
						</xs:complexContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="notes" type="xs:string"/>
			<xs:element name="EnvironmentDefinition" type="EnvironmentDefinitionType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="environmentContainerDefinitionId" type="xs:IDREF"/>
	</xs:complexType>
	<xs:complexType name="EnvironmentContainerDefinitionType">
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:simpleType name="NetworkTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Application"/>
			<xs:enumeration value="Organisation"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="NetworkType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="fenceMode" type="xs:string"/>
			<xs:element name="networkMask" type="xs:string"/>
			<xs:element name="gatewayAddress" type="xs:string"/>
			<xs:element name="primaryDns" type="xs:string"/>
			<xs:element name="secondaryDns" type="xs:string"/>
			<xs:element name="dnsSuffix" type="xs:string"/>
			<xs:element name="staticIpPool" type="xs:string"/>
			<xs:element name="ipRangeStart" type="xs:string"/>
			<xs:element name="ipRangeEnd" type="xs:string"/>
			<xs:element name="CIDR" type="xs:string"/>
			<xs:element name="shared" type="xs:boolean" default="false" minOccurs="0"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="dataCenterId" type="xs:IDREF"/>
		<xs:attribute name="dataCenterName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="ApplicationNetworkType">
		<xs:complexContent>
			<xs:extension base="NetworkType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="OrganisationalNetworkType">
		<xs:complexContent>
			<xs:extension base="NetworkType">
				<xs:sequence minOccurs="0">
					<xs:element name="peerNetworkName" type="xs:string"/>
					<xs:element name="peerEnvironmentName" type="xs:string"/>
				</xs:sequence>
				<xs:attribute name="gatewayId" type="xs:IDREF"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EnvironmentDefinitionComplexType">
		<xs:sequence>
			<xs:element name="EnvironmentDefinitionType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EnvironmentDefinitionType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="version" type="xs:string"/>
			<xs:element name="cidr" type="xs:string"/>
			<xs:element name="VirtualMachineContainer" type="VirtualMachineContainerType" maxOccurs="unbounded"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="environmentDefinitionType" type="EnvironmentDefinitionTypeType" use="required"/>
	</xs:complexType>
	<xs:simpleType name="EnvironmentDefinitionTypeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Logical"/>
			<xs:enumeration value="Blueprint"/>
			<xs:enumeration value="Physical"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="VirtualMachineContainerType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="runtimeLease" type="xs:string"/>
			<xs:element name="storageLease" type="xs:string"/>
			<xs:element name="serviceLevel" type="xs:string"/>
			<xs:element name="powerOn" type="xs:boolean"/>
			<xs:element name="deploy" type="xs:boolean"/>
			<xs:element name="domain" type="xs:string"/>
			<xs:element name="VirtualMachine" type="VirtualMachineType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Network" type="ApplicationNetworkType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="dataCenterId" type="xs:IDREF"/>
		<xs:attribute name="dataCenterName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="MetaDataType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="value" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="VirtualMachineType">
		<xs:sequence>
			<xs:element name="vmName" type="xs:string"/>
			<xs:element name="computerName" type="xs:string"/>
			<xs:element name="description" type="xs:string"/>
			<xs:element name="templateName" type="xs:string"/>
			<xs:element name="templateServiceLevel" type="xs:string"/>
			<xs:element name="storageProfile" type="xs:string"/>
			<xs:element name="customisationScript" type="xs:string"/>
			<xs:element name="VMOrder" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The order of the VM in in the sequence for powering on (ascending order) and off (reversed order high to low)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="1000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStartDelay" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The Start delay</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStopDelay" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The Stop delay in seconds</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:int">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="180"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStartAction" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The VM Start Action. One of none, powerOn</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="powerOn">
							<xs:annotation>
								<xs:documentation>This will set the VM to Power On when started by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="none">
							<xs:annotation>
								<xs:documentation>This will set the VM do nothing when started by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="VMStopAction" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The VM Stop Action. One of powerOff, guestShutdown</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="powerOff">
							<xs:annotation>
								<xs:documentation>This will set the VM to Power Off when stopped by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="guestShutdown">
							<xs:annotation>
								<xs:documentation>This will set the VM to Shutdown when stopped by the vApp.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="cpuCount" type="xs:integer"/>
			<xs:element name="memory" type="xs:integer"/>
			<xs:element name="memoryUnit" type="xs:string"/>
			<xs:element name="hardwareProfile" type="xs:string"/>
			<xs:element name="hatype" type="xs:string" minOccurs="0"/>
			<xs:element name="Storage" type="StorageType" maxOccurs="unbounded"/>
			<xs:element name="NIC" type="NICType" maxOccurs="unbounded"/>
			<xs:element name="MetaData" type="MetaDataType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="NICType">
		<xs:sequence>
			<xs:element name="indexNumber" type="xs:integer"/>
			<xs:element name="primary" type="xs:boolean"/>
			<xs:element name="ipAssignment" type="xs:string"/>
			<xs:element name="Interface" type="InterfaceType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="networkID" type="xs:IDREF"/>
		<xs:attribute name="networkName" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="StorageType">
		<xs:sequence>
			<xs:element name="indexNumber" type="xs:integer"/>
			<xs:element name="size" type="xs:integer"/>
			<xs:element name="sizeUnit" type="xs:string"/>
			<xs:element name="busType" type="xs:string"/>
			<xs:element name="busSubType" type="xs:string"/>
			<xs:element name="deviceMount" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="DataCenterType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="GatewayType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="NAT" type="NATType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="NATType">
		<xs:sequence>
			<xs:element name="appliedOn" type="xs:string"/>
			<xs:element name="originalSourceIpOrRange" type="xs:string"/>
			<xs:element name="translatedSourceIpOrRange" type="xs:string"/>
			<xs:element name="enabled" type="xs:boolean"/>
			<xs:element name="DNAT" type="DNATType" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="DNATType">
		<xs:sequence>
			<xs:element name="translatedPort" type="xs:string"/>
			<xs:element name="protocolType" type="xs:string"/>
			<xs:element name="protocolOriginalPort" type="xs:string"/>
			<xs:element name="protocolIcmpType" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:simpleType name="ProviderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SKYSCAPE"/>
			<xs:enumeration value="AWS"/>
			<xs:enumeration value="MICROSOFTAZURE"/>
			<xs:enumeration value="GOOGLECOMPUTE"/>
			<xs:enumeration value="IBMSOFTLAYER"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="InterfaceType">
		<xs:sequence>
			<xs:element name="interfaceNumber" type="xs:integer" minOccurs="0"/>
			<xs:element name="staticIpPool" type="xs:string"/>
			<xs:element name="networkMask" type="xs:string"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="staticIpAddress" type="xs:string"/>
			<xs:element name="isVip" type="xs:boolean"/>
			<xs:element name="VRRP" type="xs:integer" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== UKHomeOffice/eba-envbuild-tool/eba-acloud/aCloudClient/src/test/resources/aws/awsBridgeTestEnvironment.xml
<GeographicContainer id="_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" xsi:schemaLocation="http://ebsa.ipt.com/AgnosticCloudConfig-1.0 AgnosticCloudConfig-1.0.xsd">
    <account>Home Office</account>
    <region>IPT-AWS</region>
    <EnvironmentContainer id="_2">
        <name>np</name>
        <provider>AWS</provider>
        <Environment id="_5" environmentContainerDefinitionId="_3">
            <name>EBSAD-20086-ENV</name>
            <notes>EBSAD-20086-ENV</notes>
            <EnvironmentDefinition environmentDefinitionType="Physical" id="_6">
                <name>EBSAD-20086-ENVDEF</name>
                <version>1.5</version>
                <cidr>10.16.0.0/16</cidr>
                
                <VirtualMachineContainer dataCenterId="_4" id="_7">
                    <name>EBSAD-20086-VMC</name>
                    <description>EBSAD-20086-VMC</description>
                    <runtimeLease></runtimeLease>
                    <storageLease></storageLease>
                    <serviceLevel>Home Office IPT (IL2-DEVTEST-BASIC)</serviceLevel>
                    <powerOn>true</powerOn>
                    <deploy>true</deploy>
                    <domain></domain>
                    <VirtualMachine id="_9">
                        <vmName>EBSAD-20086-VM</vmName>
                        <computerName>EBSAD-20086-VM</computerName>
                        <description>EBSAD-20086-VM</description>
                        <templateName>ami-abb22edc</templateName>
                        <templateServiceLevel>Home Office IPT (IL2-DEVTEST-BASIC)</templateServiceLevel>
                        <storageProfile>9-76-3-BASIC-Any</storageProfile>
                        <customisationScript></customisationScript>
                        <cpuCount>2</cpuCount>
                        <memory>4</memory>
                        <memoryUnit>GB</memoryUnit>
                        <hardwareProfile>m3.large</hardwareProfile>
                        <hatype></hatype>
                        <Storage id="_11">
                            <indexNumber>1</indexNumber>
                            <size>50</size>
                            <sizeUnit>GB</sizeUnit>
                            <busType></busType>
                            <busSubType></busSubType>
                            <deviceMount>/dev/sda1</deviceMount>
                        </Storage>
						<NIC id="_10" networkID="_8">
							<indexNumber>0</indexNumber>
							<primary>true</primary>
							<ipAssignment>StaticManual</ipAssignment>
							<Interface>
								<staticIpPool />
								<networkMask />
								<name>EBSAD-20086-NIC</name>
								<staticIpAddress>10.16.3.4</staticIpAddress>
								<isVip>false</isVip>
							</Interface>
						</NIC>
						<NIC id="_12" networkID="org1">
							<indexNumber>1</indexNumber>
							<primary>true</primary>
							<ipAssignment>StaticManual</ipAssignment>
							<Interface>
								<staticIpPool />
								<networkMask />
								<name>EBSAD-20086-ORG-NIC</name>
								<staticIpAddress>10.16.4.4</staticIpAddress>
								<isVip>false</isVip>
							</Interface>
						</NIC>
                    </VirtualMachine>
                    <Network dataCenterId="_4" id="_8">
                        <name>EBSAD-20086-VM-NET</name>
                        <description></description>
                        <fenceMode>NATROUTED</fenceMode>
                        <networkMask>255.255.255.0</networkMask>
                        <gatewayAddress>10.16.3.1</gatewayAddress>
                        <primaryDns>10.16.3.1</primaryDns>
                        <secondaryDns>10.16.3.1</secondaryDns>
                        <dnsSuffix>dns-suffix</dnsSuffix>
                        <staticIpPool></staticIpPool>
                        <ipRangeStart>10.16.3.2</ipRangeStart>
                        <ipRangeEnd>10.16.3.10</ipRangeEnd>
                        <CIDR>10.16.3.0/24</CIDR>
                        <shared>true</shared>
                    </Network>
                </VirtualMachineContainer>
            </EnvironmentDefinition>
        </Environment>
        <EnvironmentContainerDefinition id="_3">
            <name>HO_IPT_NP</name>
            <version>1.5</version>
            
            <Network dataCenterId="_4" id="org1" gatewayId="gw1">
	            <name>EBSAD-20086-ORG-NET</name>
	            <description></description>
	            <fenceMode>NATROUTED</fenceMode>
	            <networkMask></networkMask>
	            <gatewayAddress></gatewayAddress>
	            <primaryDns></primaryDns>
	            <secondaryDns></secondaryDns>
	            <dnsSuffix></dnsSuffix>
	            <staticIpPool></staticIpPool>
	            <ipRangeStart></ipRangeStart>
	            <ipRangeEnd></ipRangeEnd>
	            <CIDR>10.16.4.0/24</CIDR>
	            <shared>true</shared>
            </Network>
            <Gateway id="gw1">
            	<name>EBSAD-20086-GW</name>
            </Gateway>
            <DataCenter id="_4">
                <name>eu-west-1a</name>
            </DataCenter>
        </EnvironmentContainerDefinition>
    </EnvironmentContainer>
</GeographicContainer>

=== UKHomeOffice/eba-envbuild-tool/eba-platform/environment-build-metadata-import/src/test/resources/HO_IPT_NP_agnostic_aws.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Partial implementation (1st Virtual Machine Container, all Org Networks and Gateways) of HO_IPT_NP_PRP1 in the cloud agnostic schema -->
<GeographicContainer id="ID_1" xmlns="http://ebsa.ipt.com/AgnosticCloudConfig-1.0" xsi:schemaLocation="http://ebsa.ipt.com/AgnosticCloudConfig-1.0 AgnosticCloudConfig-1.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<account>Home Office</account>
	<region>IPT</region>
	<EnvironmentContainer id="EnvironmentContainer_1">
		<name>np</name>
		<provider>AWS</provider>
		<EnvironmentContainerDefinition id="EnvironmentContainerDefinition_1">
			<name>HO_IPT_NP_PRP1</name>
			<version>1.0</version>
			<Network gatewayId="nft000c2i2-1" id="HO_IPT_NP_TLG1_MEBC_APP_I1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_TLG1_MEBC_APP_I1</name>
				<description>Isolated network that connects the MEBC to other Management VApps</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.16.15.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.16.15.2</ipRangeStart>
				<ipRangeEnd>10.16.15.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
				<peerNetworkName>HO_IPT_NP_PRP1_COBC_MABC_MAN_I1</peerNetworkName>
				<peerEnvironmentName>Environment_2</peerEnvironmentName>
			</Network>
			<Network id="HO_IPT_NP_PRP1_COBC_MABC_MAN_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_COBC_MABC_MAN_I1</name>
				<description>Isolated network - Core Boundary Control to the Management Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.128.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.128.2</ipRangeStart>
				<ipRangeEnd>10.32.128.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
				<peerNetworkName>HO_IPT_NP_TLG1_MEBC_APP_I1</peerNetworkName>
				<peerEnvironmentName>Environment_2</peerEnvironmentName>
			</Network>
			<Network id="HO_IPT_NP_PRP1_PRZO_MABC_MAN_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_PRZO_MABC_MAN_I1</name>
				<description>Isolated network - Private Application Zone to the Management Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.144.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.144.2</ipRangeStart>
				<ipRangeEnd>10.32.144.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_DABC_MABC_MAN_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_DABC_MABC_MAN_I1</name>
				<description>Isolated network - Data Boundary Control to the Management Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.160.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.160.2</ipRangeStart>
				<ipRangeEnd>10.32.160.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_DAZO_MABC_MAN_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_DAZO_MABC_MAN_I1</name>
				<description>Isolated network - Data Zone to the Management Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.176.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.176.2</ipRangeStart>
				<ipRangeEnd>10.32.176.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_ESZO_MABC_MAN_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_ESZO_MABC_MAN_I1</name>
				<description>Isolated network - External Simulator Zone to the Management Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.192.1</gatewayAddress>
				<primaryDns>10.16.16.7</primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.192.2</ipRangeStart>
				<ipRangeEnd>10.32.192.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_COBC_DABC_APP_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_COBC_DABC_APP_I1</name>
				<description>Isolated network - Core Boundary Control to the Data Boundary Control in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.15.1</gatewayAddress>
				<primaryDns></primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.15.2</ipRangeStart>
				<ipRangeEnd>10.32.15.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_DABC_DAZO_APP_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_DABC_DAZO_APP_I1</name>
				<description>Isolated network - Data Boundary Control to the Data Zone in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.47.1</gatewayAddress>
				<primaryDns></primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.47.2</ipRangeStart>
				<ipRangeEnd>10.32.47.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Network id="HO_IPT_NP_PRP1_DABC_ESZO_APP_I1" gatewayId="nft000c2i2-1" dataCenterId="DC_1" dataCenterName="Home Office IPT NP (IL2-PROD-STANDARD)">
				<name>HO_IPT_NP_PRP1_DABC_ESZO_APP_I1</name>
				<description>Isolated network - Data Boundary Control to the External Simulator Zone in PRP1</description>
				<fenceMode>ISOLATED</fenceMode>
				<networkMask>255.255.255.0</networkMask>
				<gatewayAddress>10.32.79.1</gatewayAddress>
				<primaryDns></primaryDns>
				<secondaryDns></secondaryDns>
				<dnsSuffix></dnsSuffix>
				<staticIpPool></staticIpPool>
				<ipRangeStart>10.32.79.2</ipRangeStart>
				<ipRangeEnd>10.32.79.254</ipRangeEnd>
				<CIDR></CIDR>
				<shared>true</shared>
			</Network>
			<Gateway id="nft000c2i2-1">
				<name>nft000c2i2-1</name>
				<NAT id="Nat_1">
					<appliedOn>nft000c2i2</appliedOn>
					<originalSourceIpOrRange>185.40.8.186</originalSourceIpOrRange>
					<translatedSourceIpOrRange>10.16.0.5</translatedSourceIpOrRange>
					<enabled>true</enabled>
					<DNAT id="DNat_1">
						<translatedPort>22</translatedPort>
						<protocolType>TCP</protocolType>
						<protocolOriginalPort>22</protocolOriginalPort>
						<protocolIcmpType></protocolIcmpType>
					</DNAT>
				</NAT>
				<NAT id="Nat_2">
					<appliedOn>nft000c2i2</appliedOn>
					<originalSourceIpOrRange>185.40.8.186</originalSourceIpOrRange>
					<translatedSourceIpOrRange>10.16.0.3</translatedSourceIpOrRange>
					<enabled>true</enabled>
					<DNAT id="DNat_2">
						<translatedPort>80</translatedPort>
						<protocolType>TCP</protocolType>
						<protocolOriginalPort>80</protocolOriginalPort>
						<protocolIcmpType></protocolIcmpType>
					</DNAT>
				</NAT>
				<NAT id="Nat_3">
					<appliedOn>nft000c2i2</appliedOn>
					<originalSourceIpOrRange>185.40.8.186</originalSourceIpOrRange>
					<translatedSourceIpOrRange>10.16.0.3</translatedSourceIpOrRange>
					<enabled>true</enabled>
					<DNAT id="DNat_3">
						<translatedPort>443</translatedPort>
						<protocolType>TCP</protocolType>
						<protocolOriginalPort>443</protocolOriginalPort>
						<protocolIcmpType></protocolIcmpType>
					</DNAT>
				</NAT>
				<NAT id="Nat_4">
					<appliedOn>nft000c2i2</appliedOn>
					<originalSourceIpOrRange>10.16.0.4</originalSourceIpOrRange>
					<translatedSourceIpOrRange>185.40.8.186</translatedSourceIpOrRange>
					<enabled>true</enabled>
				</NAT>
			</Gateway>
			<DataCenter id="DC_1">
				<name>Home Office IPT NP (IL2-PROD-STANDARD)</name>
			</DataCenter>
		</EnvironmentContainerDefinition>
	</EnvironmentContainer>
</GeographicContainer>
